version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ai_content_assistant
      - JWT_SECRET=secure-jwt-secret-for-development
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_NAME=AI Content Assistant
      - ENVIRONMENT=development
      - ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ai_content_assistant
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 